# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       situations-sonar

# >> macros
# << macros
%define __provides_exclude_from ^%{_datadir}/.*$
%define __requires_exclude ^libc|libgcc_s|libjsonipc.*$

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Companion Daemon for Situations
Version:    0.0.9
Release:    9
Group:      Qt/Qt
License:    Copyright (C) Pastilli Labs - All Rights Reserved
URL:        http://www.pastillilabs.com
Source0:    %{name}-%{version}.tar.bz2
Source100:  situations-sonar.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Contacts)
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(KF5CalendarCore)
BuildRequires:  pkgconfig(libical)
BuildRequires:  pkgconfig(libmkcal-qt5)

%description
Companion Daemon for Situations


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%preun
# >> preun
systemctl disable situations-sonar
systemctl stop situations-sonar
# << preun

%post
/sbin/ldconfig
# >> post
systemctl enable situations-sonar
systemctl restart situations-sonar
systemctl daemon-reload
# << post

%postun
/sbin/ldconfig
# >> postun
systemctl daemon-reload
# << postun

%files
%defattr(-,root,root,-)
%{_bindir}
%{_bindir}/%{name}
%{_datadir}/%{name}/lib/libjsonipc.so
%{_userunitdir}/harbour-situations2application.service
%{_sysconfdir}/systemd/system/%{name}.service
# >> files
# << files
