# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       situations-sonar

# >> macros
# << macros

Summary:    Companion Daemon for Situations
Version:    0.0.1
Release:    1
Group:      Qt/Qt
License:    Copyright (C) Pastilli Labs - All Rights Reserved
URL:        http://www.pastillilabs.com
Source0:    %{name}-%{version}.tar.bz2
Source100:  situations-sonar.yaml
Requires:   systemd
Requires(preun): systemd
Requires(post): systemd
Requires(postun): systemd
BuildRequires:  pkgconfig(Qt5Core)

%description
Companion Daemon for Situations


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%preun
systemctl disable situations-sonar
systemctl stop situations-sonar

%post
systemctl enable situations-sonar
systemctl restart situations-sonar
systemctl daemon-reload

%postun
systemctl daemon-reload

%files
%defattr(-,root,root,-)
/etc/systemd/system/situations-sonar.service
%{_libdir}/systemd/user/harbour-situations2application.service
%{_bindir}/%{name}
# >> files
# << files
